trigger: 
- feature/dev-branch
pool:
  name: Gravitas01

stages:
- stage: Terraform
  displayName: Terraform Stage
  jobs:
  - job: TerraformJob
    displayName: Terraform Workflow
    steps:

    # 1️⃣ Install Terraform
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.10.5'

    # 2️⃣ Terraform Init
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        backendServiceArm: 'GravtiasServiceConnection'
        backendAzureRmResourceGroupName: 'dev-aks-rg'
        backendAzureRmStorageAccountName: 'infrastorage4480143'
        backendAzureRmContainerName: 'infracontainer'
        backendAzureRmKey: 'gravitas.tfstate'

    # 3️⃣ Terraform Fmt
    - task: TerraformTask@5
      displayName: Terraform Fmt
      inputs:
        provider: 'azurerm'
        command: 'custom'
        customCommand: 'fmt'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

    # 4️⃣ Terraform Validate
    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

    # 5️⃣ Terraform Plan
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        environmentServiceNameAzureRM: 'GravtiasServiceConnection'
